### ISSUE TITLE
Taxonomy broken link

### ISSUE THREAD

**Issue by afgalvan** [CodelyTV/refactoring-code-smells#33]
The [current URL](http://mikamantyla.eu/BadCodeSmellsTaxonomy.html) used in the README for referring to the taxonomy appears to be moved to [this one](https://mmantyla.github.io/BadCodeSmellsTaxonomy)

https://github.com/CodelyTV/refactoring-code-smells/blob/7f41096b6c7096af28f41c1c7453f468265ca854/README.md#L35

**Comment by JavierCane** [comment]
thx for the report!
